version: '3.8'
services:
  # PHP Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: website
    container_name: ItroveBill
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db # Use the service name of the MySQL service
      DB_PORT: 3306
      DB_DATABASE: itrovebill
      DB_USERNAME: manish
      DB_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: itroveDB
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: itrovebill
      MYSQL_USER: manish
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app-network

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: itroveDBWeb
    restart: unless-stopped
    ports:
      - "8090:80" # Maps port 8080 on the host to port 80 on the container
    environment:
      PMA_HOST: db
      PMA_USER: manish
      PMA_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - app-network

# Volumes for persisting database data
volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
